spring:
  application:
    name: foerderantragsverwaltung
  datasource:
    url: jdbc:h2:mem:foerderantrag
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true

logging:
  structured:
    format:
      console: ecs

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080
