include:
  - component: "gitlab.com/it-erben/components/pdf-publisher/build-publish@1.6.0"
  - component: "gitlab.com/it-erben/components/linters/lychee-lint@1.3.0"
  - component: "gitlab.com/it-erben/components/linters/yaml-lint@1.3.0"
  - component: "gitlab.com/it-erben/components/linters/markdown-lint@1.3.0"
  - component: "gitlab.com/it-erben/components/release/release@1.0.0"

stages:
  - lint
  - build
  - verify
  - release
  - deploy

lint:lychee:
  script:
    - lychee --accept 429,200 --exclude "http://localhost.*" --exclude ".*\.drawio\.png" --exclude-path ".npm-cache" --max-concurrency 4 --retry-wait-time 2 --timeout 20 --cache '**/*.md' | tee lychee-results.md

maven-test:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH
  parallel:
    matrix:
      - PROJECT_DIR:
          - labs/lab-01-setup/initial-project
          - solutions/lab-02-spring-boot-basics
          - solutions/lab-05-building-blocks
          - solutions/lab-06-clean-architecture-refactoring
          - solutions/lab-07-use-case-implementierung
          - solutions/lab-08-rest-adapter
          - solutions/lab-09-archunit
          - solutions/lab-10-context-integration
          - solutions/lab-11-querschnittsthemen
          - solutions/lab-12-testing
  script:
    - cd "$PROJECT_DIR"
    - mvn --batch-mode verify
  cache:
    key: maven-$PROJECT_DIR
    paths:
      - .m2/repository
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
