include:
  - component: "gitlab.com/it-erben/components/pdf-publisher/build-publish@1.7.0"
  - component: "gitlab.com/it-erben/components/linters/lychee-lint@1.3.0"
  - component: "gitlab.com/it-erben/components/linters/yaml-lint@1.3.0"
  - component: "gitlab.com/it-erben/components/linters/markdown-lint@1.3.0"
  - component: "gitlab.com/it-erben/components/release/release@1.0.0"
  - component: "gitlab.com/it-erben/components/maven/verify@1.2.0"


stages:
  - lint
  - build
  - verify
  - release
  - deploy

docker:
  stage: deploy
  image: docker:27
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build
      artifacts: true
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
