<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.foerderung</groupId>
    <artifactId>foerderantragsverwaltung-aggregator</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Foerderantragsverwaltung - Aggregator</name>

    <modules>
        <module>labs/lab-01-setup-und-warmup/initial-project</module>
        <module>solutions/lab-01-setup-und-warmup</module>
        <module>solutions/lab-04-building-blocks</module>
        <module>solutions/lab-05-clean-architecture-refactoring</module>
        <module>solutions/lab-06-use-case-implementierung</module>
        <module>solutions/lab-07-rest-adapter</module>
        <module>solutions/lab-08-archunit</module>
        <module>solutions/lab-09-context-integration</module>
        <module>solutions/lab-10-modulith</module>
    </modules>

</project>
